name: Test

on:
  workflow_dispatch:
  pull_request:

env:
    IMAGE_NAME: digitalearthafrica/waterbodies

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0

    - name: Activate Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11  
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Setup waterbodies test environment
      run: |
          make test-env
    - name: Run waterbodies test
      run: |
          make run-tests
          make clean

    - name: Clean waterbodies image
      run: |
          (echo y) | docker container prune
          (echo y) | docker image prune